version: '3'

services:
  frontend:
    build:
      context: ./timeman-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./timeman-app:/app
  backend:
    build:
      context: ./timeman_api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./timeman_api:/app